/* tslint:disable */
/* eslint-disable */
/**
 * Hindeara API
 * API docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProcessUserInputDto,
  ProcessUserInputResponseDto,
} from '../models/index';
import {
    ProcessUserInputDtoFromJSON,
    ProcessUserInputDtoToJSON,
    ProcessUserInputResponseDtoFromJSON,
    ProcessUserInputResponseDtoToJSON,
} from '../models/index';

export interface PlatformControllerProcessUserInputRequest {
    userId: object;
    processUserInputDto: ProcessUserInputDto;
}

/**
 * 
 */
export class PlatformsApi extends runtime.BaseAPI {

    /**
     */
    async platformControllerProcessUserInputRaw(requestParameters: PlatformControllerProcessUserInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessUserInputResponseDto>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling platformControllerProcessUserInput().'
            );
        }

        if (requestParameters['processUserInputDto'] == null) {
            throw new runtime.RequiredError(
                'processUserInputDto',
                'Required parameter "processUserInputDto" was null or undefined when calling platformControllerProcessUserInput().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{userId}/processUserInput`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProcessUserInputDtoToJSON(requestParameters['processUserInputDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessUserInputResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async platformControllerProcessUserInput(requestParameters: PlatformControllerProcessUserInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessUserInputResponseDto> {
        const response = await this.platformControllerProcessUserInputRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
