/* tslint:disable */
/* eslint-disable */
/**
 * Hindeara API
 * API docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAppDto
 */
export interface CreateAppDto {
    /**
     * 
     * @type {string}
     * @memberof CreateAppDto
     */
    httpPath: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAppDto
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the CreateAppDto interface.
 */
export function instanceOfCreateAppDto(value: object): value is CreateAppDto {
    if (!('httpPath' in value) || value['httpPath'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function CreateAppDtoFromJSON(json: any): CreateAppDto {
    return CreateAppDtoFromJSONTyped(json, false);
}

export function CreateAppDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAppDto {
    if (json == null) {
        return json;
    }
    return {
        
        'httpPath': json['http_path'],
        'isActive': json['is_active'],
    };
}

export function CreateAppDtoToJSON(json: any): CreateAppDto {
    return CreateAppDtoToJSONTyped(json, false);
}

export function CreateAppDtoToJSONTyped(value?: CreateAppDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'http_path': value['httpPath'],
        'is_active': value['isActive'],
    };
}

