/* tslint:disable */
/* eslint-disable */
/**
 * Hindeara API
 * API docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessUserInputDto
 */
export interface ProcessUserInputDto {
    /**
     * 
     * @type {string}
     * @memberof ProcessUserInputDto
     */
    recording: string;
}

/**
 * Check if a given object implements the ProcessUserInputDto interface.
 */
export function instanceOfProcessUserInputDto(value: object): value is ProcessUserInputDto {
    if (!('recording' in value) || value['recording'] === undefined) return false;
    return true;
}

export function ProcessUserInputDtoFromJSON(json: any): ProcessUserInputDto {
    return ProcessUserInputDtoFromJSONTyped(json, false);
}

export function ProcessUserInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessUserInputDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recording': json['recording'],
    };
}

export function ProcessUserInputDtoToJSON(json: any): ProcessUserInputDto {
    return ProcessUserInputDtoToJSONTyped(json, false);
}

export function ProcessUserInputDtoToJSONTyped(value?: ProcessUserInputDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recording': value['recording'],
    };
}

