/* tslint:disable */
/* eslint-disable */
/**
 * Hindeara API
 * API docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessUserInputResponseDto
 */
export interface ProcessUserInputResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ProcessUserInputResponseDto
     */
    recording: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessUserInputResponseDto
     */
    uiData: string;
    /**
     * 
     * @type {number}
     * @memberof ProcessUserInputResponseDto
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessUserInputResponseDto
     */
    appId: number;
}

/**
 * Check if a given object implements the ProcessUserInputResponseDto interface.
 */
export function instanceOfProcessUserInputResponseDto(value: object): value is ProcessUserInputResponseDto {
    if (!('recording' in value) || value['recording'] === undefined) return false;
    if (!('uiData' in value) || value['uiData'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('appId' in value) || value['appId'] === undefined) return false;
    return true;
}

export function ProcessUserInputResponseDtoFromJSON(json: any): ProcessUserInputResponseDto {
    return ProcessUserInputResponseDtoFromJSONTyped(json, false);
}

export function ProcessUserInputResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessUserInputResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recording': json['recording'],
        'uiData': json['uiData'],
        'userId': json['userId'],
        'appId': json['appId'],
    };
}

export function ProcessUserInputResponseDtoToJSON(json: any): ProcessUserInputResponseDto {
    return ProcessUserInputResponseDtoToJSONTyped(json, false);
}

export function ProcessUserInputResponseDtoToJSONTyped(value?: ProcessUserInputResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recording': value['recording'],
        'uiData': value['uiData'],
        'userId': value['userId'],
        'appId': value['appId'],
    };
}

